apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiahia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiahia
  strategy: {}
  template:
    metadata:
      labels:
        app: hiahia
    spec:
      containers:
      - name: server
        image: registry.cn-shanghai.aliyuncs.com/ayane/hiahia
        imagePullPolicy: Always
        command:
          - server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: hiahia
spec:
  type: ClusterIP
  selector:
    app: hiahia
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080

  
